// Generated by https://quicktype.io
export interface IclienteNatural {
  id?: number;
  codigo: string;
  ruc: string;
  nombre1: string;
  nombre2?: string;
  apellido1: string;
  apellido2: string;
  correo?: string;
  celular?: string;
  cumple?: string;
  foto?: string;
  publish?: number;
}
